language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install -r requirements.txt --use-wheel"
  - "pip install coveralls --use-wheel"
  - "pip install -e ."
script:
  - coverage run --source=vumi_http_retry `which trial` vumi_http_retry
after_success:
  - coveralls
